target-version = "py39"
src = ["pi-pair"]

[lint]
select = ["E4", "E7", "E9", "F", "I", "B", "C90", "PLE", "PLW0602", "RUF100"]

[lint.per-file-ignores]
"pi-pair/mini_chat.py" = ["E402"]
"pi-pair/scripts/**" = ["E402"]

[lint.mccabe]
max-complexity = 20

[lint.isort]
known-first-party = ["pair", "tests"]
